### ISSUE TITLE
Suggestion:  Need more feedback on current metal.

### ISSUE THREAD

**Issue by MentalMouse** [legobmw99/Allomancy#11]
Right now, A Mistborn has got eight anonymous gauges, with sometimes a highlight box to show which pair is selected.  You really should at least have a pop-up-text saying what pair you just switched to.

**Comment by legobmw99** [comment]
I like how it currently is - the learning curve isn't that steep, and anyone familiar with the series would have a pretty easy time of figuring out which is which. That said, I might look into adding a config option to display some text about the current selected group.
