### ISSUE TITLE
Feature Request:  Something else to do with lerasium (also stackability)

### ISSUE THREAD

**Issue by MentalMouse** [legobmw99/Allomancy#12]
So, I ate my lerasium, and went around taking on various Ruins and other dungeons... where I found several more nuggets of lerasium.  Too bad I'm in SSP, so it's is now useless, and unstackable to boot.

Could lerasium be given some role in crafting new wonders, perhaps something inspired by the newest of the books in the sequence?

**Comment by legobmw99** [comment]
I can't think of anything interesting for it to do. I had considered at one point making you lose the ability when you died, but that seemed too harsh

**Comment by jdickson8** [comment]
You could potentially make lerasium make you either more powerful or have a larger quantity of metals to burn like in the book similar to Vin using the power of the mist or the well of ascension. So the more you eat the more power of Preservation you have. That shouldn't be too hard to implement at least the increasing the quantity burnable. The making more powerful would be hard though.

**Comment by MentalMouse** [comment]
Increasing your reservoirs is certainly an option.  Another would be to use it to craft devices powerful enough that it's appropriate to limit their number in the world.  

The big thing that comes to mind is a Minecraft-styled form of the "cubes" from _The Bands of Mourning_:   A placeable block that can be loaded with metals and continuously use the chosen power over a broad area (say, the usual 16-block range).  That is, with iron it would draw in all loose items; with brass it would pacify all mobs in range; With pewter or tin it would apply the effect to all players nearby, beacon-like;  Perhaps with zinc it would cause hostiles to flee, which is also an interesting idea for normal play.  

Some less-thematic options:
- Could be used to craft one of the new Totems of Undying.  (Advantages:  No new items, consumable.)
- Powerful or overly-useful permanent pet, perhaps unkillable or able to respawn at your own spawn point when killed.
- Dimensional pocket home; if you don't want to add your own dimension, you could locate it in the far reaches of the End or above the Nether ceiling, surrounded by bedrock.  Or it could simply provide a reliable portal leading above the Nether ceiling, with a return portal created there.

**Comment by MentalMouse** [comment]
Addendum on the cube:  With iron or steel, it would also locate ores, with lines coming from the device.  We probably wouldn't want it to push/pull items that didn't have a line-of-sight to the device, that would just be awkward.

**Comment by legobmw99** [comment]
Hm, I do like the cube idea. Cannoically they are made with Harmonium, not Lerasium, but it could still work. I'll leave this issue open and look into it in a couple weeks when I have time

**Comment by CayJoBla** [comment]
Perhaps if Atium is added in the future you could combine it with the Lerasium for Harmonium devices

**Comment by MentalMouse** [comment]
The problem is that Atium is pretty problematic to implement, on multiple counts.  OK, perhaps you could do ghost images ahead of a mob based on the AI, but PvP would be a bit more difficult.

**Comment by legobmw99** [comment]
Basically any implementation of Atium would be practically impossible, as even a singleplayer only solution would require effectively running the game twice, once for the prediction and once for the action.

I did consider adding it and having it grant complete immortality (for all of 5 seconds until it runs out), but that didn't seem fun

________________________________

**Comment by CayJoBla** [comment]
Obviously there is no way to detect future player behavior to make atium shadows for players, or electrum shadows for oneself, but a system could be implemented where players burning atium "dodge" 90-100% of damage from other players and mobs, and they "catch" any arrows/projectiles thrown at them.  Burning electrum or atium could make the burner able to successfully attack another atium burner.  Not sure how difficult or possible it would be to implement mob shadows, but if not the same system could be applied.

**Comment by jdickson8** [comment]
That would be a fairly simple way of implementing Atium that would remain mostly similar to the books while still adding functionality to minecraft that would be fun. Then you could just have the 2 god metals and not have to do all the rest of the advanced metals which would be more difficult like gold and cadmium.

**Comment by MentalMouse** [comment]
Note that "impossible" metals can always be squelched by declaring that the versions available in Minecraft are impure or misalloyed.  Those attempting to burn them anyway could be afflicted with various noxious effects....  Gold would actually be pretty easy -- just do an unequipped Steve? regardless of the player's current skin, or even depict an avatar from one of Minecraft's predecessor games.
