### ISSUE TITLE
The End... of a Mistborn??

### ISSUE THREAD

**Issue by MentalMouse** [legobmw99/Allomancy#13]
When I killed the Ender Dragon, I found a piece of Bronze flakes, instead of the (Mystical Agriculture) Supremium I was expecting.  It was a while later before I realized that I'd somehow been demoted back to a Misting, but I'd been distracted by other things (mostly follow-up to the End), and hadn't been using Allomancy, so I can easily believe that the demotion happened at the Ender Dragon's death.

Was this intended, or just weirdness?

**Comment by legobmw99** [comment]
This is certainly not intended, and I can't imagine why it would happen. What mods were you using, and would any of them have any reason to mess with your player save file when you killed the enderdragon?

________________________________

**Comment by MentalMouse** [comment]
I am using quite a lot of mods, list to follow.  I don't think any of them would have an obvious reason to mess with the savefile;  Looking at my file dates, I've most recently updated AromaBackup, Biomes O'Plenty, JEI, and maybe Mystical Agriculture.  (Not sure quite where in that list the End fight came, but I'm pretty sure it was after the BOP update.)  Quark is also a possible suspect just because it seems to have fingers into everything.  ;)

Modlist:
> [1.11.2]UncraftingTable-1.7.1-pre14.jar
achunkloader-1.11.2-1.2.0.jar
allomancy-2.6.1.jar
ArmorDamageRecalc-1.11.x.jar
Aroma1997Core-1.11.2-1.2.0.0.jar
AromaBackup-1.11-2.1.0.0.jar
autism-1.0.1.jar
AutoRegLib-1.1-4.jar
Baubles-1.11-1.4.2.jar
BedBugs-1.11-1.1.4.jar
BiomesOPlenty-1.11.2-6.1.0.2193-universal.jar
cfm-4.1.2-mc1.11.2.jar
Chameleon-1.11-3.0.2.jar
CraftTweaker-1.11.2-3.0.24.jar
DynamicLights-1.11.2.jar
ExtraRails-1.11-1.2.1.jar
fairylights-2.1.0-1.11.2.jar
Forgelin-1.2.0.jar
GiacomosBookshelf-1.11.2-1.1.jar
GiacomosFishingNet-1.11.2-1.5.1.jar
GiacomosFoundry-1.11.2-1.3.12.jar
GraveStone Mod 1.7.2.jar
hempfarmer-1.11-1.7.6.jar
jei_1.11.2-4.3.3.270.jar
journeymap-1.11.2-5.4.3.jar
LLOverlayReloaded-1.1.3-mc1.11.2.jar
malisiscore-1.11.2-5.1.1.jar
malisisswitches-1.11.2-4.1.0.jar
Minions-1.11.2
Minions-1.11.2-20170326.jar
multistorage-1.11.0-1.3.5.jar
mysticalagriculture[1.11.2]-1.5.2c.jar
NoMoreRecipeConflict-0.6(1.11).jar
Notes-1.11.2-1.0.0.jar
OpenEye-1.11.2-0.8.jar
PackingTape-1.11.0-0.6.1.jar
PassthroughSigns-1.11-2.1.1.jar
PetBat-1.11.2.jar
Psi-r1.1-47.jar
Quark-r1.2-90.jar
RealBench-1.11.2-1.3.2.jar
realfilingcabinet-1.11.2-1.2.49.jar
recycler-1.4.1-1.11.2.jar
redstonepaste-mc1.11.2-1.7.4.jar
reptilemod-1.11.2-3.6.2-65.jar
resources
Ruins-1.11.2.jar
ShadowMC-1.11-3.7.4.jar
Shelf
shetiphiancore-1.11.0-3.4.3.jar
SimpleTeleporters-1.11.2-2.0.2.jar
StorageDrawers-1.11.2-4.2.1.jar
VisibleArmorSlots[1.11.2]-3.1.1.jar
Waddles-1.11-0.5.1.jar
Waystones_1.11.2-3.0.13.jar
WearableBackpacks-1.11.2-2.0.0.jar
WIT-1.11-1.0.22-41.jar

**Comment by legobmw99** [comment]
Have you tried killing the dragon again? Maybe in a test word? Does a similar result occur? Could you possible film it? I'm trying to pin down the issue before just trying my mod with each and every combination of mods you have installed (which will probably never be feasible)

**Comment by MentalMouse** [comment]
I may do that over this weekend, but I'm not set up for filming it.  I will try to set up backups before-and-after, and keep the logs.

**Comment by MentalMouse** [comment]
OK, I did it, and confirmed that I got demoted to Misting (and gifted with copper flakes) when I actually returned to the Overworld post-dragon.

Here's [a Dropbox folder](https://www.dropbox.com/sh/flgtmm5efk9j01c/AADNfObPjREO8JVlzw1gJsbka?dl=0) with "before" and "after" Aroma Backups.  After considering how much I'd explored, I did this in a new test world.

**Comment by MentalMouse** [comment]
Thanks for fixing this!  Just out of curiosity, can you explain what went afoul?

**Comment by legobmw99** [comment]
For some reason, the game resets the player file when returning from the end. All I had to change was change the code that kept your mistborn status when you died to also do it
