### ISSUE TITLE
Soothing: Skellies keep shooting, other mobs just wander

### ISSUE THREAD

**Issue by MentalMouse** [legobmw99/Allomancy#15]
Allomancy 2.6.2, MC 1.11.2

When Soothed, skeletons repeatedly fire in the same direction (east?) regardless of potential targets.

Also, there's not much you can do with Soothed mobs -- I had hopes of at least being able to lead them around (into a zoo ;-) ), but you still can't put leads on them, and they don't seem to follow you or anything, much less fight for you (presumably that last would require combining Soothing with Rioting).

**Comment by legobmw99** [comment]
I can't reproduce the bug you describe. 

And yeah, it's pretty sparse on features when it comes to the emotional metals. The game places a lot of limitations on what I can really have them do.
