### ISSUE TITLE
Mod not Loading (1.12)

### ISSUE THREAD

**Issue by TBDPrism** [legobmw99/Allomancy#21]
I downloaded the recommended version of forge for 1.12 and the version of the mod for 1.12 and dragged the mod into the "mods" folder. Whenever I load Minecraft it always crashed as soon as it opens. Is this a bug with my forge or with the version of the mod, or did I install anything wrong? Please help.

**Comment by DatrixTHLK** [comment]
https://gist.github.com/DatrixTHLK/1816fac6907d9728304f5a557a8f01a5 

This is the crash log that I am getting
Minecraft 1.12
Forge 14.21.1.2405
Allomancy 2.7.1

Other than downloading this mod and putting it into my mods folder and starting up minecraft with the latest version of forge this is what happens. Do I need a coremod?

**Comment by legobmw99** [comment]
Changes to Forge recently have caused this issue. I will try to update the mod as soon as I can.

**Comment by DatrixTHLK** [comment]
I see. Thanks for responding.
