### ISSUE TITLE
Allomancy-whitelist.txt and metadata

### ISSUE THREAD

**Issue by NullMagic** [legobmw99/Allomancy#25]
Alright, I'd like to begin by saying that as a long time fan of Sanderson (ever since the debut of Elantris) I am quite pleased to not only see but also play with this mod.

Now, on to why I'm here instead of just on the Curse page. The whitelist, it's a wonderful idea however it's current format makes it difficult to fine tune. So far as I can tell it doesn't use metadata at all, in fact my one attempt to introduce metadata has resulted in the entries simply being ignored.

what this seems to mean is that when there are many blocks with the same name, but different metadata they all get added to the list and all count as being metal despite whether they actually all are or not.

So what I'm wondering is, would it be possible to make the Whitelist also include metadata?

**Comment by legobmw99** [comment]
I'm not able to actually code for a few days, but I'm replying to let you
know I saw this. I agree that it isn't ideal, and I myself am not
completely happy with the system. It was a feature added on request of
another user, and it was done as quickly as possible largely pulling from
other mods. I will revisit it sometime soon to try to improve it. Not only
would I like to support metadata, but I'd also like some sort of
version-tracking to allow me to push updates to the whitelist without just
telling people to delete the file every update. It would also be nice for
servers to force their own whitelist on to the client, but that is another
can of worms.

Now, I am not super sure how easy this is to actually implement. Metadata
itself is being phased out, and I do want to maintain the ability to add
all types of a given item. This is further complicated by the fact that the
same list is also used for items and blocks. So, from a technical
standpoint, this may not be feasible (or would require a much more complex
data format than just a list, possibly JSON or something similar), but rest
assured I will try my best in the future.

**Comment by NullMagic** [comment]
Thanks for the quick response! I honestly have no idea how hard it is either, hopefully it's not too difficult, but thanks for looking into it either way!

**Comment by legobmw99** [comment]
I know this issue has been dormant for a long time, because the honest answer was the way Minecraft did metadata was so poor it wasn't really worth doing. That said, this issue should go away with the update to 1.13, as metadata is being completely removed. Any properly made mod should have different names for every unique item and block starting on that version. Because of this, I am going to close the issue (though note, the issue would not _actually_ be resolved until the update to 1.13)
