### ISSUE TITLE
Console Text in 1.12.1

### ISSUE THREAD

**Issue by Alaberti** [legobmw99/Allomancy#27]
Presumably other versions as well. I see this text a lot in the console:

com.legobmw99.allomancy.util.RecipeItemVial:func_77569_a:32

Is there a way to only have this print to the log and nowt the console? Thanks.

**Comment by Alaberti** [comment]
Was this fix ever pushed out to a build? Thank you.

**Comment by legobmw99** [comment]
It wasn't and I can't promise when that may happen. Feel free to build your own jar, it is not as hard as it seems
