### ISSUE TITLE
elixirs don't appear on 1.12.2

### ISSUE THREAD

**Issue by lag42** [legobmw99/Allomancy#29]
put the jar file in 1.12.2, hope for the best and then see that there is no way to fill your metal bar, allomantic elixir does strangely enough appear but it still doesn't work or even react to you attempting to drink it

**Comment by legobmw99** [comment]
Could you give more details? Screenshots of the item, your metal bar, perhaps even a video of you drinking it?
Are you in Creative or Survival? Mistborn or Misting?

________________________________

**Comment by lag42** [comment]
In survival as a misting, metal bar appears normal and trying to drink the allomantic elixir just acts the same as if you were holding right click with a benign item

**Comment by legobmw99** [comment]
The elixir is filled, correct?
Was this world previously running an earlier version of the mod?

________________________________

**Comment by lag42** [comment]
Running the latest version and the metal bar only had trace amounts

**Comment by legobmw99** [comment]
Please get a video if you can, I can’t recreate the issue

________________________________

**Comment by lag42** [comment]
sorry for the late response, ive attached a photo which hopefully describes a lot
![2017-12-13_14 50 31](https://user-images.githubusercontent.com/22325011/33962001-a9d31840-e015-11e7-80a2-fd447611b5b1.png)
 the recipes are gone too and i'm gonna try and figure out what mod is causing this the 3 missing textures are from another mod which forgot to keep those items from appearing in other tabs

**Comment by legobmw99** [comment]
If you launch a separate instance with just my mod, does it work as expected? It sounds like you’re having some conflicts that are beyond my mod

________________________________

**Comment by lag42** [comment]
actually this isn't a conflict as i thought, it doesn't work in an instance with just allomancy

**Comment by legobmw99** [comment]
Did you actually craft the vial together with any metals to fill it?

**Comment by lag42** [comment]
i did now and it works, i don't know why i didn't try that
