### ISSUE TITLE
Strange initial whitelist file with IC2

### ISSUE THREAD

**Issue by evhub** [legobmw99/Allomancy#30]
With IC2 enabled, the whitelist file is by default populated by duplicate entries that look like <https://gist.github.com/evhub/8754e9a0346c52ed892662fa98a0ecf2>.

**Comment by evhub** [comment]
Also, with BiomesOP, I'm getting
```
biomesoplenty:flower_1
biomesoplenty:plant_1
```
added by default as well, which are clearly not made of metal.

**Comment by legobmw99** [comment]
I appreciate the report. The automated part of the whitelist functionality is pretty quick-and-dirty, and I expect most people who use the mod in large packs to tweak it themselves. There is not really a better way of doing it that I'm aware of. I can stop duplicates, but even that is fairly low priority
