### ISSUE TITLE
Forge 1.14 (allomancy-3.0.0-beta3) - Opening Inventory Crashes Game

### ISSUE THREAD

**Issue by taigamerlin** [legobmw99/Allomancy#35]
I removed all mods except this one, and tried running the game. Everything was fine until I opened my inventory, when the game immediately crashed.

**Comment by WardBrian** [comment]
Can I get a crash log?

**Comment by legobmw99** [comment]
Can I get a crash log?

**Comment by taigamerlin** [comment]
I'm using TLauncher, I'm not sure where to find the crash log. However,
though I recreated this a few times, after a bit the same thing happened
without the mod, so there must be some other cause. Sorry to waste your
time, but thank you so much for the extremely fast response and the
incredible mod!!
