### ISSUE TITLE
Creates confict with Journey Map

### ISSUE THREAD

**Issue by snostormjp** [legobmw99/Allomancy#38]
Some how using this mod with journey map causes journey map to display on waypoints pillars in the wrong location, the waypoints are set correctly for teleport and as point on map just the pillars of light are incorrect.  Not certain what allomancy does to cause this.

**Comment by legobmw99** [comment]
Can I get a version number, forge and JM version, and a modlist? A screenshot or any sort of weird log message would also help.

Does the problem go away when Allomancy is removed?

**Comment by snostormjp** [comment]
I was using a mod pack loaded through at-launcher, the forge version was 1.15.2 on  forge  31.1.25. I went through and disabled all mods except allomancy 4.0.1 and journey map 5.7.0beta1 .
The Image below shows the mini map with player almost on way-point but beacon  off in distance .
also removing allomancy fixes the issue. 
![image](https://user-images.githubusercontent.com/22462487/82341918-ec0da100-99e8-11ea-92e7-e311adc834ff.png)

**Comment by legobmw99** [comment]
I'm going to wait for JourneyMap to leave beta on 1.15 to look into this issue much further. It is quite likely the problem will work itself out on their end

**Comment by snostormjp** [comment]
That's cool, will wait till then

**Comment by legobmw99** [comment]
Has this persisted?

**Comment by snostormjp** [comment]
I jump around versions alot so not certain.
