### ISSUE TITLE
common_setup error

### ISSUE THREAD

**Issue by hutonahill** [legobmw99/Allomancy#39]
i get this error on my windows desktop (running windows 10) and on two of my mac users (running OSX 10.14.6), but not one of them.

it reads:

**Allomancy (allomancy) encountered an error during the common_setup event phase**
net.minecraft.world.biome.Biome.func_222280_a(Lnet/minecraft/world/gen/feture:Lnet/minecraft/world/gen/feature/Feature;Lnet/minnecraft/world/gen/feature/IFeatureConfig;Lnet/minecraft/world/gen/placement/Placement;Lnet/minecraft/world/gen/placement/IPlacementConfig;)Lnet/minecraft/world/gen/feature/ConfiguredFeature;

here are the log files for the mac and the windows versions.
[latestMac.txt](https://github.com/legobmw99/Allomancy/files/4783705/latestMac.txt)
[latestWindows.log](https://github.com/legobmw99/Allomancy/files/4783695/latestWindows.log)

i have also included a log of where i did not have the problem:
[latestMacSuccess.log](https://github.com/legobmw99/Allomancy/files/4783765/latestMacSuccess.log)

**Comment by legobmw99** [comment]
In the successful log, you are using Forge 31.2.9, in both unsuccessful you are using 31.2.0 - have you tried updating?

**Comment by hutonahill** [comment]
just tested it with 31.2.20 and id didn't work.

also didn't work with 31.2.9.  same error

**Comment by legobmw99** [comment]
I haven't been able to recreate this issue. I'll try poking around some more

**Comment by legobmw99** [comment]
I've been unable to recreate this. I'm about to post another version with some minor tweaks, please try that

**Comment by hutonahill** [comment]
just tried it on a totally new computer and it worked. here is a log. 
[latest.txt](https://github.com/legobmw99/Allomancy/files/4807173/latest.txt)

as of right now I am not reopening the thread as I have yet to be able to test the new mod on any of the user I know don't work.

**Comment by hutonahill** [comment]
just tested with my windows computer and it works!! here is the log if you want it:
[latest.log](https://github.com/legobmw99/Allomancy/files/4807286/latest.log)
