### ISSUE TITLE
Astral Sorcery compatibility issue

### ISSUE THREAD

**Issue by RurouniTim** [legobmw99/Allomancy#52]
I've been playing on a multiplayer server I host for a few friends including this mod and have experienced a visual glitch with an Astral Sorcery structure where the starfield is not displayed when stepping in Celestial Gateways. Functionally, they still work if I can find the exact location where I'm needing to look, but it's still difficult to do so. I've included a video showing what I'm referring to. When I tried removing mods, I was able to narrow down that this mod (currently version 4.2.1) was consistently causing this visual bug. 

https://youtu.be/9dFqlsaAEM8

Information:
-Minecraft Version 1.16.4
-Forge Version 35.1.37
-Astral Sorcery version 1.13.9
-Allomancy 4.2.1

Attempts to fix the issue includes:
-Changing graphics settings
-Downloading the server save and attempting in single player
-Removing resource pack
-Removing other mods
-Toggling Allomancy hud
-Tweaking configs for both mods

If anyone knows the cause and/or has any suggestions, I'd be happy to hear them.

Thank you.

PS, even if there's not any easy fix for this, I'd still like to take a moment to to say that I appreciate the mod dev's time and effort in creating and maintaining this mod. Being a fan of Minecraft and Sanderson, I really enjoy being able to engage both interests simultaneously. Minor compatibility issue aside, I'm having a great time with this mod and thoroughly enjoy its place in my modpack!

**Comment by legobmw99** [comment]
I'm not familiar with AS too deeply, what is the expected behavior here?

**Comment by RurouniTim** [comment]
Typically it works like a teleporter between different multiblock structures. To determine which multiblock you teleport to, it displays a starfield with a golden star indicating valid options. They are positioned based on the actual locations of the multiblock structures. When crouching or holding right click, it displays a graphic that initiates the teleport. I've posted a short video showing the standard behavior when Allomancy isn't installed.

https://youtu.be/zqqtPVhhmEo

**Comment by legobmw99** [comment]
If you hide the Allomancy HUD (there is a keybinding for this, but it may be unbound by default) does that effect it? I'll try to take a look myself later

**Comment by legobmw99** [comment]
I've found and fixed the bug - it will be included in the next allomancy update (which should be soon, sorry to make you wait!)

Please close your issue in the AS repo, it was my fault not theirs!

**Comment by RurouniTim** [comment]
I just closed it now. Thank you for being so prompt in identifying the issue and finding a solution! It is greatly appreciated by me and my server!
