### ISSUE TITLE
4.3.0-pre3 Some iron made objects aren't considered metal

### ISSUE THREAD

**Issue by ResMaster** [legobmw99/Allomancy#58]
Some iron made objects aren't considered metal when iron or steel is being burned. These items are:

- Shield
- Bucket of Salmon/Pufferfish/Tropical Fish/Cod
- Blast Furnace
- Chain
- Tripwire Hook
- Crossbow
- Smithing Table
- Stonecutter
- Koloss Blade (in the books it's metallic while ingame it's made of stone)

Also, when a player wears metal, they can see the blue line drawn towards themselves.

**Comment by remotedeck** [comment]
also

- Chipped Anvil
- Damaged Anvil
