### ISSUE TITLE
Crash when Pushing on minecart in a server

### ISSUE THREAD

**Issue by remotedeck** [legobmw99/Allomancy#59]
[crash-2021-05-17_10.20.53-server.txt](https://github.com/legobmw99/Allomancy/files/6493284/crash-2021-05-17_10.20.53-server.txt)
[crash-2021-05-17_10.14.37-server.txt](https://github.com/legobmw99/Allomancy/files/6493285/crash-2021-05-17_10.14.37-server.txt)
[crash-2021-05-17_10.28.34-server.txt](https://github.com/legobmw99/Allomancy/files/6493286/crash-2021-05-17_10.28.34-server.txt)
[crash-2021-05-17_10.44.00-server.txt](https://github.com/legobmw99/Allomancy/files/6493287/crash-2021-05-17_10.44.00-server.txt)

**Comment by legobmw99** [comment]
Is this Allomancy 4.2?

**Comment by remotedeck** [comment]
oh yeah whoops you probably fixed it in the newer version
