### ISSUE TITLE
Minecraft Server crashing during loading

### ISSUE THREAD

**Issue by CelticChristoph** [legobmw99/Allomancy#6]
Minecraft Version: 1.10.2
Forge version: 12.18.3.2185

This crash was specifically during the server launch, not client launch. I feel this is probably important? Large list of mods, so I won't list them here at the moment, but can if necessary (list will be contained in error report though).

Report here:
http://pastebin.com/nx8KAEcA

Any questions, lemme know.

**Comment by legobmw99** [comment]
Thank you for reporting this issue, it was a simple error on my part. The fix is included in 2.2.1, which is currently waiting for approval on CurseForge. It should be available soon
