### ISSUE TITLE
Staged Lerasium

### ISSUE THREAD

**Issue by Crazydude323** [legobmw99/Allomancy#60]
I'd like to suggest a config option to make eating a Lerasium nugget unlock a single random Allomancy power, rather than unlocking all of them at once. They seem common enough from loot chests, and this would provide a form of progression for the mod, where you unlock more and more metals as you find or make more Lerasium. After eating enough, you could of course still unlock every power.

**Comment by SonnyLonglegs** [comment]
Thanks for putting this here. I forgot there was a Github to put this.

**Comment by legobmw99** [comment]
I'm curious how possible this is with the existing 'Quest' mods like FTB Quests. I don't see this as being a direction I want to take the mod, but I'm happy to try to support it in a modpack or otherwise

**Comment by SonnyLonglegs** [comment]
Can you add a command to add a random power? Currently you can pick one single metal power to give, but if there was an "add random" option, you could cover both items. For building quests, you could pick a metal to give as a reward, but with a random mod you could add a "lootbox" option. I could see this as a 17th option on the command menu.

**Comment by legobmw99** [comment]
Anything besides a random power that would be useful?

**Comment by SonnyLonglegs** [comment]
Amounts you can store? Like by default, I think you can hold 16 in a reserve. Perhaps a a command to increase one or all by an amount? I'd love that in survival, but I don't know how it could be done. 

I'd imagine that being something like  /metal increase iron (random would fit here) 10. Increase or decrease capacity, and by an amount.

For a questing modpack, changing the starting power to be either none or a specific metal would be useful. Perhaps it's a story modpack and you start with specifically 10 iron capacity or something. Or for a server, if you want to limit access to metals and buy them with a shop of some sort to keep griefing down. (Can you grief with bendalloy lag?)
