### ISSUE TITLE
The Metal Selection Wheel no longer will open

### ISSUE THREAD

**Issue by ClaudiusMinimus** [legobmw99/Allomancy#67]
I am updating my pack, [Create on a Potato PC](https://www.curseforge.com/minecraft/modpacks/create-on-a-potato) and updated Allomancy to 4.3.2. The Metal Selection Wheel no longer will open when I press the "v" key. I checked the bindings and there are no conflicts.

Allomancy 4.3.2
Minecraft 1.16.5
Forge 36.2.8

**Comment by legobmw99** [comment]
What version were you using prior? Could you post settings.txt or wherever your keybinds are stored if not there?

**Comment by ClaudiusMinimus** [comment]
Thank you for getting back to me!
version 4.3.1
[keybindings.txt](https://github.com/legobmw99/Allomancy/files/7282292/keybindings.txt)

**Comment by legobmw99** [comment]
It seems like it's not even listed there. Does it show up in the mods list on the home Screen?

Are you using a mod to manage keybindings?

**Comment by ClaudiusMinimus** [comment]
![image](https://user-images.githubusercontent.com/17887664/135949742-724e57b2-678d-4129-8b38-e84330714527.png)

**Comment by ClaudiusMinimus** [comment]
I'm using Controlling

**Comment by ClaudiusMinimus** [comment]
This has not been uploaded to Curseforge yet:
[Create Potato 1.16.5-1.27.0.zip](https://github.com/legobmw99/Allomancy/files/7282322/Create.Potato.1.16.5-1.27.0.zip)

**Comment by legobmw99** [comment]
Does it work without those mods? I won't be able to test myself until tomorrow

**Comment by ClaudiusMinimus** [comment]
I'll try it now

**Comment by ClaudiusMinimus** [comment]
I just did a fresh install of MC 1.16.5 with Forge 36.2.8 with Allomancy 4.3.2 and no other mods. Here is a screenshot of the bindings page
![image](https://user-images.githubusercontent.com/17887664/135950678-89375977-ea89-4f3e-ba51-33336913ad91.png)
Here is the normal HUD **with** burn "v" key activated 
![image](https://user-images.githubusercontent.com/17887664/135950761-5b1b209f-0e77-4d79-8c15-33454fcadcdf.png)
Here is the normal HUD **without** burn "v" key activated
![image](https://user-images.githubusercontent.com/17887664/135950929-4b11692d-569c-4fa8-a851-8ec180a59aba.png)

**Comment by ClaudiusMinimus** [comment]
There is no Metal Selection Wheel

**Comment by legobmw99** [comment]
It is intended behavior that the wheel not show if you have only one metal. If you eat a lerasium does it show up?

**Comment by ClaudiusMinimus** [comment]
Ah, you changed the behavior! It shows up now
Thank you

**Comment by legobmw99** [comment]
Yep, changed in 4.3 to match what it did in pre-4.0 versions

**Comment by ClaudiusMinimus** [comment]
I will make a note of it in my changelog for this version so other players don't ask the same question. TBH I think the old way was more intuitive. Regardless, I love your mod!
Thanks again,
CM
