### ISSUE TITLE
States on Readme mod is ... updated for ... 1.18.1

### ISSUE THREAD

**Issue by ClaudiusMinimus** [legobmw99/Allomancy#69]
Your [Readme](https://github.com/legobmw99/Allomancy/blob/main/README.md) on this github states:
> This mod is currently updated for Minecraft 1.18.1 and Forge 39.0.0

However, the most recent published version is [allomancy-4.4.0.jar](https://www.curseforge.com/minecraft/mc-mods/allomancy/files/3518858) for 1.17.1

**Comment by legobmw99** [comment]
The current state of this repo is the mod has been updated to 1.18. I have not released a version yet because I need to change ore generation and have not yet had the time

**Comment by ClaudiusMinimus** [comment]
Thanks for the update! I look forward to adding it back to my pack, Create
on a Potato PC!
