### ISSUE TITLE
1.18.2 - Raw Ores and Ingots don't appear to be properly tagged for their materials

### ISSUE THREAD

**Issue by SonnyLonglegs** [legobmw99/Allomancy#73]
It makes for annoying little problems like not being Tinkers meltable or able to be processed in Thermal machines.

**Comment by legobmw99** [comment]
Is there a consensus on what tags should be applied to these? When I first updated it seemed like there were multiple options floating around

**Comment by SonnyLonglegs** [comment]
forge:raw_materials/materialnamehere appears to be the standard, at least to get recognized by Thermal and Tinkers. Looking at Allomancy's raw ores, the only tag any of them have is "minecraft:parrots_spawnable_on".
