### ISSUE TITLE
Allomantic lines not rendering for Mac 

### ISSUE THREAD

**Issue by SpeedyZ500** [legobmw99/Allomancy#76]
When playing on a Mac, no Allomantic line appears, visual bug the powers themselves work fine except of course the power that are purely visual in effect, be it iron/steel lines the lines from electrum and gold, and apparently the bronze lines as well, Tim however does work, (tested on a LAN world other player saw all lines just fine),  though not sure why this happens, I have checked with just the allomancy mod and same thing I know this is unlikely to get fixed, I have been playing with the latest version of the mod, allomancy 4.5.3, forge 40.1.59, no resource packs, partials all, no optifine or other optimization mod, on PC all works as expected/intended

**Comment by legobmw99** [comment]
I unfortunately do not have a Mac to test. Can you give me some more information about your system?

I believe if you hold F3+C for 10 seconds it will crash the game. The crash log that produces should have enough information for me to investigate

**Comment by SpeedyZ500** [comment]
https://pastebin.com/XPPwwSGY

**Comment by SpeedyZ500** [comment]
My Mac is an M1 MacBook Pro

**Comment by SpeedyZ500** [comment]
I wonder if the issue is related to the fact that Minecraft Java versions older than 1.18 has to go through Rosetta 2 to be run on apple silicone, because other than being interperated by Rosetta Minecraft Java should work exactly the same on Mac and PC, but it is also possible it has something to do with metal, apples graphics engine

**Comment by SpeedyZ500** [comment]
https://pastebin.com/qyt4v4J4
Turns out that it is still not working, still no alloymancy lines, it isn't rosetta

**Comment by SpeedyZ500** [comment]
Sorry wrong log here's the correct one: https://pastebin.com/a0AjVU40

**Comment by SpeedyZ500** [comment]
I've discovered it is working on 1.19.2, it doesn't work if you aren't using the official launcher, likely because the unofficial launcher is incompatible with the ARM version of Java for launching Minecraft, and therefore has to run through rosetta, and something with rosetta is making it so that it can't render the Allomantic lines, I'll just close this as can't fix

**Comment by SpeedyZ500** [comment]
I've also found a work around, for multiMC, that allows you to play even 1.18.2 natively
