### ISSUE TITLE
Server Crashes randomly during uptime.

### ISSUE THREAD

**Issue by Suddenfoil3** [legobmw99/Allomancy#8]
At random intervals while playing the server crashes. Me and my friend have narrowed it down to what we think is burning a metal while loading chunks. We are also using two other mods: JourneyMap and VeinMiner.

Minecraft Version: 1.11.2
Forge Version:13.20.0.2214

Crash Report:
http://pastebin.com/Zfj03smF

**Comment by legobmw99** [comment]
I think I located the issue. Did either of you happen to run out of metals right when it crashed?

**Comment by Suddenfoil3** [comment]
I've been drinking a pewter vial everytime the server goes down, because it wipes any metals you've stored, so I'd have to say probably. I'll try and see if that's the problem.

**Comment by Suddenfoil3** [comment]
Okay, after testing it a few times my answer is Yes it does crash when you run out of metal. Also to correct an error, it seemed like the server wiped my metal storage because I ran out metal during the time of the crash. In turn I drank another vial thinking it was the server and not me actually running out. Sorry for the confusion.

**Comment by Suddenfoil3** [comment]
Thanks! You make great mods!
