### ISSUE TITLE
Enhancement suggestion: configurable whitelist/blacklist for active metal reg

### ISSUE THREAD

**Issue by SpeedyZ500** [legobmw99/Allomancy#82]
So I was looking hat how you auto detect the metal list (private static final Pattern ACTIVE_METAL_REGEX = Pattern.compile(
            ".*(iron|steel|tin_|pewter|zinc|brass|copper|bronze|duralumin|chromium|nicrosil|gold|electrum|cadmium|bendalloy|lead_|silver|platinum|nickle).*");), and I was wondering if you would be able to add a config option in the alloymacy Minecraft configs that would allow you to add metal names to the active metal regex, and if you could also create a metal name blacklist, as there are some metals that I would consider heavily infused in some mods (I.e. soulsteel, or manasteel), but science their names contain steel, are added to the metals config, this also would make it easier to add more metals to the config, it would of course mean that your pattern could not be a final, and may require a different data structure, or some fancy uses of code somewhere else, but from my understanding it should be possible, though it would likely mean that load times would increase, but not as much as say, adding code that somehow screens all recipes to determine if an item contains metal somewhere in its crafting tree

**Comment by legobmw99** [comment]
This regex is only used to generate the default whitelist, so it's a bit of a hack. That said, it seems like the things you're requesting are probably easy to manually edit the list in the config?

**Comment by SpeedyZ500** [comment]
I am just trying to give an example as to why something like that would be beneficial, my situation is probably in the 10,000 items, and since I am playing back in 1.18.2 (to use tinkers construct) I probably should just make a 1.18 fork that modifies the REGEX to save me time, will still end up having to delete a bunch of metals that I would consider invested in such a way that you wouldn’t be able to push off it, like how an alloymancer has difficulty pushing off a metal mind, or how one would be unable to push off an honorblade, shardblade, or piece of shard plate.

**Comment by SpeedyZ500** [comment]
If you were asking if it would be easy to edit the regex list in the config, the answer to that would be maybe, it depends on how the data structure is setup to work

**Comment by SpeedyZ500** [comment]
And I did look at the code, I understand that it is designed to go through and look at all the items that have the metal names in the item name, which is how you end up with being able to push off of iron wood trees or steel leaf trees in mods like biomes o plenty or the twilight forest

**Comment by legobmw99** [comment]
I think this is not something I'd like to support
