### ISSUE TITLE
Add metals to vials not work on 1.16.5 server modded

### ISSUE THREAD

**Issue by brav0doce** [legobmw99/Allomancy#85]
Hi, the mod works perfectly in singleplayer but when I play on my server it does not allow me to add any metal to the vials, the only thing I can do on the server is to take the vial with the 16 metals out of the creative.
Version: 1.16.5
I have added the allomancy mod to the FTB University 1.16 mod pack. 
any suggestions?

**Comment by legobmw99** [comment]
I am unfortunately unable to support versions that far back. Creative or using `/give` with custom NBT data will work if crafting does not
