### ISSUE TITLE
Bendalloy not affecting Furnaces

### ISSUE THREAD

**Issue by MrPogostyc** [legobmw99/Allomancy#87]
I seem to remember Bendalloy's speed bubble affecting the speed of which Furnaces smelt items. It doesn't seem to be working anymore. 

Is it also possible for Speed bubbles to effect the furnaces in the Mod Iron Furnaces?

**Comment by legobmw99** [comment]
What version are you using? This was broken at one point but I believe I fixed it in 5385c56

**Comment by MrPogostyc** [comment]
Latest for 1.18.2 according to Curse Forge! Is it possible that you patched this for only 1.19.2?

Allomancy: Version 4.5.3 - Forge 40.2.0 - 1.18.2

If you aren't supporting 1.18.2 anymore, I might give coding a second shot and see if i can patch it myself, (with your permission of course) 
![image](https://user-images.githubusercontent.com/59030023/225807427-8d283b71-6779-4a39-a917-e0c77bc8106e.png)

**Comment by legobmw99** [comment]
Yeah the patch was only applied in 1.19. I imagine the same code would work in the earlier versions though

**Comment by legobmw99** [comment]
49513d0b754443798fb73524b84951d14e274f6d

**Comment by legobmw99** [comment]
4.5.4 has been released with this issue fixed
