### ISSUE TITLE
Add Keybinds for specific Metals as a mistborn

### ISSUE THREAD

**Issue by MrPogostyc** [legobmw99/Allomancy#88]
Title! i think this would be very helpful without having to use the radial menu to enable specific metals. This may also come with an overhaul of the Vial HUD. perhaps, replace the vials with the symbols, and have the color "fill" upwards depending on the amount in your system.

**Comment by legobmw99** [comment]
This is already in the mod, but pre-1.9 you need to enable "advanced_keybinds" in the config file. 

They are all unbound by default
