### ISSUE TITLE
(1.19.2) Duralumin crash

### ISSUE THREAD

**Issue by RurouniTim** [legobmw99/Allomancy#89]
I've been getting crashesin 4.6.1 whenever I attempt to burn duralumin. I've tried it with different versions of 1.19.2 forge and also tried removing the other mods in the pack but I'm still consistently crashing. Do you know what the cause is and how I might fix it?

https://pastebin.com/pDKWHSwh

PS, thanks again for your information on datapacks and how to modify orespawns as it relates to this mod. It's sent me down a very fun, yet very time consuming, rabbithole that's lead to me tweaking crafting recipes for my personal playstyles.

**Comment by SILVERXAVI** [comment]
also to version 1.18.2

**Comment by legobmw99** [comment]
Patch releases for both 1.19 and 1.18 are out with this bug fixed
