### ISSUE TITLE
[1.20.1] crash on server

### ISSUE THREAD

**Issue by cylian914** [legobmw99/Allomancy#90]
Allomancy crash on server when starting, its because PowersClientSetup.register() (in modules/powers) its executed even on server. 
Something like this make it run on server
![image](https://github.com/legobmw99/Allomancy/assets/73445993/88f38768-50ce-4a1f-9ca3-fa16f466b8f2)

**Comment by legobmw99** [comment]
Can you share a crash log?

**Comment by legobmw99** [comment]
Thanks. I'll try to investigate this weekend. I don't think that particular code has changed in a long time, but it's possible forge has changed something underlying it
