### ISSUE TITLE
The game will report an error when I click the Duralumin in the Roulette

### ISSUE THREAD

**Issue by toofarbut** [legobmw99/Allomancy#91]
[crash-2023-08-26_21.40.13-client.txt](https://github.com/legobmw99/Allomancy/files/12445463/crash-2023-08-26_21.40.13-client.txt)
The game version is 1.19.2,the mod version is 4.6.1,I like this mod,but the problem is  annoying

**Comment by legobmw99** [comment]
Duplicate of #89, update to 4.6.4 if you can
